### ISSUE TITLE
群满了，能整一个2021考研群嘛？

### ISSUE THREAD

**Issue by msxfXF** [ningzimu/See_you_in_BUPT#13]
如题

**Comment by Jelly27** [comment]
同求，两个群都拒绝加入了

**Comment by ningzimu** [comment]
> 同求，两个群都拒绝加入了

您好，考研群都是会定期清理的，一般情况下都会保证一定的余量供新成员加入。如果您在加群过程中遇到什么问题，可以私信现任群主进行解决。

**Comment by JuGyang** [comment]
请有问题的同学发邮件给我联系：jugyang@163.com
