### ISSUE TITLE
请问还会更新2020的数据吗？

### ISSUE THREAD

**Issue by Hanyuyu** [ningzimu/See_you_in_BUPT#15]

**Comment by ningzimu** [comment]
你好，目前我已经毕业了。近一年来我已经很少关注北邮考研的实时信息，故我本人已经不能及时更新最新的北邮考研数据了，**目前本仓库处于停更状态**，敬请谅解。最新的考研信息可以加考研群了解，里面有学弟学妹们负责整理通知北邮计算机相关考研信息。

另外请同学们看本汇总时一定要**注意信息的时效性**，在考研群中及时留意北邮相关的考研动态，比如最近的**院系合并**、**调剂政策**等重要信息！

**如果有同学有意继续更新本汇总或者在本汇总的基础上继续开发一个新的仓库，可以联系我（619883006@qq.com）。**

**Comment by Hanyuyu** [comment]
好的，感谢
