### ISSUE TITLE
有些链接失效了，请问会修复么

### ISSUE THREAD

**Issue by 160405103** [ningzimu/See_you_in_BUPT#17]

**Comment by ningzimu** [comment]
请问是哪些链接失效了呢？这个仓库里面引用的大部分都是github内部链接。如果外部链接失效了，并且我还能找到对应的资源。那么我可以尝试修复。
另外，目前这个仓库已经停更了，里面很多信息都过期了～～

**Comment by 160405103** [comment]
好的，依旧感谢
