### ISSUE TITLE
文件能否压缩一下

### ISSUE THREAD

**Issue by justorez** [ningzimu/See_you_in_BUPT#2]
如题，自己的网络环境太差，下载巨慢。。。能不能麻烦北邮学长把文件打个压缩包再提交。

**Comment by ningzimu** [comment]
## 不是很明确你的需求。
你是觉得**这个项目体积过大不利于clone到本地**，还是想**打包下载所有文件**呢？

- 对于前者，目前不能压缩，原因有二。
1.不利于后续更新。 此项目不定时更新，如果每次都要把新文件加到压缩包里的话，工作量较大。
2.将文件打包成压缩包上传后，readme里面的链接就会全部失效，那样这个项目就失去了存在的意义。
> 可以考虑的改进方法：转移图床，从而降低本项目体积。

- 对于后者，非常不建议这样做。
1. 做这个项目的初衷就是觉得报考文件太多太乱且缺乏必要的说明，没有条理，所以在readme里系统整理了一下。
2. 文件再多，信息再全，不去看没有任何用处。所以打包下载文件本身没有任何意义。所有文件均在readme中做了下载链接，需要看那一块信息时可以在readme文件中迅速定位，这样做极大的提高了效率、节省了考研学子宝贵的时间。

**感谢您的反馈~**

**Comment by justorez** [comment]
OK，明白了~
