### ISSUE TITLE
建议加一个组号的的对应关系。

### ISSUE THREAD

**Issue by jotline** [ningzimu/See_you_in_BUPT#8]
尤其是计算机院，组号进行了调整，建议加入说明和解释。

**Comment by ningzimu** [comment]
感谢您的反馈，这个问题我已经发现了，所以汇总里面保留了往年的招生专业目录。同学们可自行对比近两年的招生专业目录观察组号的变化。我也会在后续的更新中，在相应位置加入一些提醒和说明。
