### ISSUE TITLE
2020年貌似没有计算机技术, 换成了电子信息

### ISSUE THREAD

**Issue by imckh** [ningzimu/See_you_in_BUPT#9]
2020年貌似没有计算机技术, 换成了电子信息

**Comment by ningzimu** [comment]
是的，今年改革了，原来的计算机专硕（计算机技术）、通信专硕（电子信息工程）、软件专硕（软件工程）都合并成了现在的**电子信息**专业。除了名字改变了，其他都没变。
另外，由于最近一段时间比较忙，没有再继续追踪北邮考研的最新资料与相关政策，很多第一手的时效数据没有拿到。因此不敢轻易更新，所以目前本项目属于停更状态，**请大家在看汇总信息的时候务必留意时效性**。
**希望热心的同学可以继续更新下来**，可以给我发PR我来合并，如果就这样断掉比较可惜。
